### ISSUE TITLE
handle self-intersecting polygons during geom operations

### ISSUE THREAD

**Issue by caver456** [ncssar/sartopo_python#20]
a polygon with two vertices at the same position causes shapely to throw a self-intersecting polygon exception.  Handle this gracefully - either return False with a logging error message, or, find out how to proceed with the intended operation.

**Comment by caver456** [comment]
Here's the json that causes a self-intersecting polygon - notice that points 4 and 6 are identical - not even sure how this happens:

```
            "geometry": {
               "coordinates": [
                  [
                     [
                        -121.11063465106375,
                        39.296670749090204
                     ],
                     [
                        -121.11110671985037,
                        39.29497695748482
                     ],
                     [
                        -121.10908969867117,
                        39.29484410935141
                     ],
                     [
                        -121.10887512194998,
                        39.29663753788397
                     ],
                     [
                        -121.10887512194998,
                        39.29660432666198
                     ],
                     [
                        -121.10887512194998,
                        39.29663753788397
                     ],
                     [
                        -121.11063465106375,
                        39.296670749090204
                     ]
                  ]
               ],
               "type": "Polygon"
            },
```

and the error message:

```
ERROR:shapely.geos:TopologyException: Input geom 1 is invalid: Self-intersection at or near point -121.10887512194998 39.296604326661978 at -121.10887512194998 39.296604326661978
INFO:shapely.geos:Self-intersection at or near point -121.10887512194998 39.296604326661978
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    sts.expand(a11,b11)
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\sartopo_python.py", line 1105, in expand
    result=targetGeom|p2Geom
  File "C:\Users\caver\AppData\Roaming\Python\Python37\site-packages\shapely\geometry\base.py", line 278, in __or__
    return self.union(other)
  File "C:\Users\caver\AppData\Roaming\Python\Python37\site-packages\shapely\geometry\base.py", line 685, in union
    return geom_factory(self.impl['union'](self, other))
  File "C:\Users\caver\AppData\Roaming\Python\Python37\site-packages\shapely\topology.py", line 70, in __call__
    self._check_topology(err, this, other)
  File "C:\Users\caver\AppData\Roaming\Python\Python37\site-packages\shapely\topology.py", line 38, in _check_topology
    self.fn.__name__, repr(geom)))
shapely.errors.TopologicalError: The operation 'GEOSUnion_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x0C8FCB70>
```
![image](https://user-images.githubusercontent.com/18752102/123564160-18a7f680-d76d-11eb-8d95-34bc336ef98b.png)

Looks like just four points - but drag one out at the top left corner:

![image](https://user-images.githubusercontent.com/18752102/123564219-5c026500-d76d-11eb-86fe-a6e877be43a0.png)

**Comment by caver456** [comment]
reading around, here are some suggestions for turning self-intersecting polygons into valid ones:
- buffer(0) - but there are several comments that this has problems i.e. deleting the larger portion of a bowtie
- convex hull - clearly not an option since the polygon may contain convex portions
- fix it yer dang self, since none of the automated suggestions are bulletproof

Since sartopo seems to be creating these near-duplicate points at almost-identical coordinates in the middle of the list of coordinates, it's probably safe to make an attempt to resolve these rounding-error-style problems by pruning almost-identical duplicate points; then, if the polygon is still self-intersecting, abort the operation and gracefully inform the user.

**Comment by caver456** [comment]
oops, the bad geometry is actually b11 (I read the nestings wrong in the json) - zooming in on the problematic top right corner during edit:

![image](https://user-images.githubusercontent.com/18752102/123644085-e7194480-d7d9-11eb-909e-85135ee8c768.png)

**Comment by caver456** [comment]
turns out the geom operations are fine with duplicate points; it's the spurs that cause them to be non-simple.  So we need a function to remove the spurs (a,b,c,b,d --> a,b,d where b,c,b is the out-and-back single-point spur).  Single-point spur removal is easy; if the spur is more than one point, then something is truly fubar about the polygon and we shouldn't try to fix it with code anyway.
