### ISSUE TITLE
deal with ShapelyDeprecationWarning messages

### ISSUE THREAD

**Issue by caver456** [ncssar/sartopo_python#36]
During crop:

> C:\Users\caver\Documents\GitHub\plans_console\sartopo_python.py:1375: ShapelyDeprecationWarning: __getitem__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
>   for r in result[1:]:
> C:\Users\caver\Documents\GitHub\plans_console\sartopo_python.py:1375: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
>   for r in result[1:]:

**Comment by caver456** [comment]
It is time... now on Shapely 2.0.2 and the geometry operations seem to be failing.  Discovered by Steve during testing of the signed GET issue.

**Comment by caver456** [comment]
Not sure what the Feb 25 2022 comment refers to...

With Shapely 2.0.2, this is the error in question:

20:42:58 [sartopo_python:2489:CRITICAL] Uncaught exception:
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\test.py", line 54, in <module>
    sts.cut('AB','zz') # cut area assignment using line
    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\sartopo_python.py", line 1838, in cut
    rids.append(self.editFeature(id=targetShape['id'],geometry={'coordinates':[list(result[0].exterior.coords)]}))
                                                                                    ~~~~~~^^^
TypeError: 'MultiPolygon' object is not subscriptable

**Comment by caver456** [comment]
Getting .geoms like so

```
        elif isinstance(result,MultiPolygon):
            ##### EDIT FEATURE is used to update the original feature information (geometry)
            resultGeoms=result.geoms
```

returns a sequence of polygons; trying to slice it like so

`for r in resultGeoms[1:]:`

gives this error

```
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\sartopo_python.py", line 1849, in cut
    for r in list(resultGeoms[1:]):
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MultiPolygon' object is not iterable
```

interesting... it can be iterated, just not sliced... must be due to overridden functions in that class or a class it inherits.

Found a way to turn it into a list that can be sliced, from [this question](https://gis.stackexchange.com/a/460134/19306):

`            for r in [g for g in resultGeoms][1:]:`

(the list comprehension turns it into a list, which can be sliced)

**Comment by caver456** [comment]
After first commit:
testing a simple crop:

```
15:29:41 [sartopo_python:2250:INFO] crop: target=z  boundary=AA
15:29:41 [sartopo_python:2496:CRITICAL] Uncaught exception:
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\test.py", line 55, in <module>
    sts.crop('z','AA')
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\sartopo_python.py", line 2282, in crop
    result=self.intersection2(targetGeom,boundaryGeom)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\sartopo_python.py", line 2085, in intersection2
    mpcoords=[(p.x,p.y) for p in mp]
             ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MultiPoint' object is not iterable
15:29:41 [sartopo_python:684:INFO] SartopoSession instance deleted for map PVTGT.
```

**Comment by caver456** [comment]
all complex cut operations are working as expected
