### ISSUE TITLE
add functions to get account data in various formats

### ISSUE THREAD

**Issue by caver456** [ncssar/sartopo_python#50]
for radiolog

**Comment by caver456** [comment]
This issue was moving along pretty well, until trying getAccountInfo for an internet session.  This happens regardless of whether the session has an associated map before the getAccountInfo call.  Geometry operations, queries, etc all run correctly if a map is open - but getAccountInfo dies:

```
12:14:42 [sartopo_python:530:INFO] Getting account data:
12:14:42 [sartopo_python:532:INFO]   sending GET request to https://sartopo.com/sideload/account/11UEE9.json?json=%7B%22full%22%3Atrue%7D
12:14:42 [sartopo_python:534:INFO] response text:{"code":401,"message":"login required","status":"error","timestamp":1671912882195}
12:14:42 [sartopo_python:539:ERROR]   accound data request returned response code 401.  Aborting.
12:14:42 [sartopo_python:2618:CRITICAL] Uncaught exception:
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\test.py", line 45, in <module>
    print(sts.getMapList('NCSSAR'))
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\sartopo_python.py", line 554, in getMapList
    self.getAccountData()
  File "C:\Users\caver\Documents\GitHub\sartopo_python\sartopo_python\sartopo_python.py", line 540, in getAccountData
    raise STSException
sartopo_python.STSException
```

If the session already has a map, that means the userdata post request was already sent (during sendUserData).  What else is needed by getAccountData that isn't needed by the other geometry operations in the same session?  Does the get request need to be signed?  So far, only post requests have been signed.

**Comment by caver456** [comment]
In chrome devtools, watching network traffic for the browser window, beginning with a sartopo.com window which is logged out, the only interesting things that happen during login are:
1) the google auth things
2) GET https://sartopo.com/sideload/constants.json?ts=1671818660771 - return value includes a bunch of generic icons and layers stuff
3) GET <account>.json - same as the getAccountData request in question, but with no url-encoded payload.

Maybe 2 or 3 actually accomplish the login?  Trying it out now...

**Comment by caver456** [comment]
Nope, it's neither of those.  2 (sideload/constants) returns the expected json, and 3 (sideload/\<account\>.json with no payload also returns 401 'login required'.

**Comment by caver456** [comment]
Had a theory: the requests.session object (self.s=requests.session() is the first thing that happens in __init__), and is used for most of the requests in the code, and was hopefully already logged in.  The theory is that I sent the account data request NOT using self.s therefore not using the logged-in session.  But, that's not the case, all the requests in the code in question are using self.s.

**Comment by caver456** [comment]
Tried signing the get request in the same manner as post requests, just in case that's actually required; still got 401.

We know that this works from an interactive session - so maybe the oath login-from-google is really required.  Still, seems strange that the oath login isn't required for any of the other requests.

**Comment by caver456** [comment]
Tried intentionally editing the POST hashed data to see what happens when an incorrectly signed request is sent - this is the reponse:

05:19:31 [sartopo_python:1037:INFO] response code = 401
05:19:31 [sartopo_python:1096:INFO] response:<Response [401]>
05:19:31 [sartopo_python:1105:WARNING] response status other than "ok":  {'code': 401, 'message': 'User not logged in', 'status': 'error', 'timestamp': 1673443172213}

So the code is the same (401) but the message is slightly different ('User not logged in' vs 'login required').  Still, this is enough to make a guess that the 401 response in the GET request is also do an incorrectly signed request.  So - compare the pre-hased request text in more detail and revise the pre-has GET request body.

**Comment by caver456** [comment]
Resolved this 401 mystery with the help of Matt J and Steve K.

basically: send a signed GET request to https://sartopo.com/api/v1/acct/<acctID>/since/0 with json=’’

The discovery that was holding up progress for months was: In the data to be hashed, make sure you include the newline after the expires timestamp string.  The hashed data must have a newline after the URL tail, and another newline after the expires timestamp.

That realization should clear the logjam for this issue and for #48.

**Comment by caver456** [comment]
Additional info just received: GET requests for secret maps must be signed (this part might always have been the case); team maps are now secret by default; and new throttling / speedbumps have been introduced.  So: creating a new issue for signed GET requests, which will enable the fixing of this issue too.  The previous comment, and emails from around that time, should show the way.

**Comment by caver456** [comment]
Picking back up on this issue, now that the signed GET feature is in place.

There are actually a few tasks to take care of here:

- [ ] ensure proper pre-hashed data: "GET /api/v1/acct/<accountID>/since/0<newline><expires_ms><newline>" per notes from 2/16/23
- [ ] allow mapless SartopoSession (make new function openMap; don't call it from setupSession; call it from init if needed, and allow calling it later from client code)

both of these are working on the old temp file sartopo_python_authTest.py, but, that file also has apparently-unnecessary auth code; so, taking the important parts of that file, while minimizing modifications to and signed-GET-related code (or any other code) is the goal.

**Comment by caver456** [comment]
confirmed MAI's (Mutual Aid Incidents formerly Events) work with the existing code, and appear as just another group account

**Comment by caver456** [comment]
Expanded the name of this issue, to include #48 and other functions

- [ ] get list of maps (names and IDs) for account, sorted chronologically (the original title of this issue)
- [ ] #48
- [ ] get full nested list of maps of all accounts - can be used by downstream tools to make a full map chooser GUI
- [ ] list all team account memberships

**Comment by caver456** [comment]
QA complete for all four permissions!
